apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: dev
resources:
- https://github.com/Aamir-raza-1/all.git/backend?=v0.0.3
replicas:
- name: nginx-deployment
  count: 1
images:
- name: nginx
  newTag: 1.14.2