apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: dev
# resources:
# - resources/vcluster-declarative.yml
# helmGlobals:
#   chartHome: https://github.com/Aamir-raza-1/all.git
helmCharts:
- name: vcluster
  releaseName: vcluster
  namespace: tenant-1 // Values needs to be replaced
  valuesFile: dev-values.yml
#   # Commented in case have local helm chart.
#   # All available options 
  version: 0.4.4
  repo: https://charts.loft.sh